<?php

/**
 * Implements hook_theme().
 */
function user_liveitchina_theme() {
  return array(
    'liveitchina_profile_user' => array(
       'variables' => array(
         'data' => NULL,
         'user' => NULL,
         'profile'=> NULL,
       ),
       'file' => 'user_liveitchina.pages.inc',
    ),
  );
}

/*
 * Implements hook_menu().
 */
function user_liveitchina_menu() {
  $items['user/%user/promote'] = array(
    'file' => 'user_liveitchina.pages.inc',
    'title' => 'Promote my Profile',
    'access callback' => 'user_edit_access',
    'access arguments' => array(1),
    'page callback' => 'user_liveitchina_promote',
    'type' => MENU_NORMAL_ITEM,
    'page arguments' => array(1),
  );
  $items['user/%user/demote'] = array(
    'file' => 'user_liveitchina.pages.inc',
    'title' => 'Remove from promotion of my Profile',
    'access callback' => 'user_edit_access',
    'access arguments' => array(1),
    'page callback' => 'user_liveitchina_demote',
    'type' => MENU_NORMAL_ITEM,
    'page arguments' => array(1),
  );
  $items['user/%user/reviews'] = array(
    'title' => 'My Reviews',
    'title callback' => 'user_liveitchina_title_callback',
    'title arguments' => array(1),
    'access callback' => 'user_edit_access',
    'access arguments' => array(1),
    'page callback' => 'user_liveitchina_my_reviews',
    'menu_name' => 'menu-liveitchina',
    'page arguments' => array(1),
    'file' => 'user_liveitchina.pages.inc',
  );

  return $items;
}

function user_liveitchina_title($type){
  $title = 'Promote Yourself';
  switch ($type){
    case 'exchange_partner':
      $title = 'Promote Yourself as Exchange Partner';
    break;
    case 'tutor':
      $title = 'Promote Yourself as Tutor';
    break;
  }
  return t($title);
}

/*
 * Implements hook_menu_alter().
 */
function user_liveitchina_menu_alter(&$items) {
  //$items['user/%user']['title callback'] = 'user_liveitchina_user_page_title';
  $items['user/%user/edit']['title'] =  t('Edit');
  $items['user/%user/relationships/received']['type'] = MENU_NORMAL_ITEM;
  $items['user/%user/relationships/sent']['type'] = MENU_NORMAL_ITEM;

  //$items['user/%/reviews/my-review']['type'] = MENU_NORMAL_ITEM;

  /*/change the display of tutor and student connections
  $items['user/%user/relationships/list']['type'] = MENU_NORMAL_ITEM;
  $items['user/%user/relationships/5']['type'] = MENU_NORMAL_ITEM;
  $items['user/%user/relationships/3']['type'] = MENU_NORMAL_ITEM;
  $items['user/%user/relationships/6']['type'] = MENU_NORMAL_ITEM;
  $items['user/%/relationships/tutor']['type'] = MENU_LOCAL_TASK;
  $items['user/%/relationships/student']['type'] = MENU_LOCAL_TASK;
  $items['user/%/relationships/all']['type'] = MENU_LOCAL_TASK;

  //* /
  $items['user/%user/relationships/3']['type']['page callback'] = 'user_liveitchina_page';
  $items['user/%user/relationships/3']['type']['file'] = 'user_liveitchina.pages.inc';
  //*/
}
function user_liveitchina_title_callback($account){
  $name = is_object($account) ? format_username($account) : '';
  return t("@name's Reviews", array('@name'=>$name));
}

function user_liveitchina_user_page_title($account){
  return t('My Profile');
}

/*
 * Implements hook_user_view_alter().
 */
function user_liveitchina_user_view_alter(&$build) {
}

/*
 * Implements hook_field_info_alter
 */
function user_liveitchina_field_info_alter(&$info) {
  
}

/*
 * Implements hook_form_ID_alter();
* User Profile Form
*/
function user_liveitchina_form_user_profile_form_alter(&$form, &$form_state, $form_id) {

  if (isset($_GET['pass-reset-token'])){
    drupal_goto(variable_get('logintoboggan_redirect_on_confirm','profile-user/'. arg(1) .'/edit'));
  }

  $form['#pre_render'][] = 'user_liveitchina_form_user_profile_form_alter_weight';
  foreach ($form as $fid => $form_value){
    if ($fid == 'metatags'){
      $form[$fid]['#access'] = FALSE;
    }

    if (is_array($form[$fid]) && isset($form[$fid]['#type']) && $form[$fid]['#type'] == 'fieldset') {
      $form[$fid]['#collapsible'] = FALSE;
    }
  }
}

function user_liveitchina_form_user_profile_form_alter_weight($elements) {
  $element_weights = array(
    'picture' => 1,
    'account' => 2,
    'l10n_client' => 3,
    'timezone' => 3,
    'privatemsg' => 4,
    'metatags' => 5,
    'locale' => 6,
    'ckeditor' => 7,
    'signature_settings' => 9,
    'user_relationship_node_access' => 10,
  );
  foreach ($element_weights as $eid=>$value){
    $elements[$eid]['#weight'] = $value;
  }
  return $elements;
}

/*
 * Implements hook_form_ID_alter();
* User Profile Form
*/
function user_liveitchina_form_profile2_edit_user_form_alter(&$form, &$form_state, $form_id) {
  
  $options_city = _liveitchina_city_dropdown_options();
/*
  if (isset($form_state['values']['profile_user']['field_city']['und'][0]['tid'])) {
    $selected = $form_state['values']['profile_user']['field_city']['und'][0]['tid'];
  }
  elseif(isset($form['profile_user']['field_city']['und']['#default_value'][0])) {
    $selected = $form['profile_user']['field_city']['und']['#default_value'][0];
  }
  else {
    $selected = key($options_city);
  }

  //add #ajax for the city
  $form['profile_user']['field_city']['und']['#options'] = $options_city;
  $form['profile_user']['field_city']['und']['#ajax'] = array(
      'callback' => 'liveitchina_dependent_dropdown_city_callback',
      'wrapper' => 'dropdown-district-replace',
  );

  $form['profile_user']['field_district']['und']['#prefix'] = '<div id="dropdown-district-replace">';
  $form['profile_user']['field_district']['und']['#suffix'] = '</div>';
  $form['profile_user']['field_district']['und']['#attributes']['class'][] = 'enabled-for-ajax';
  $form['profile_user']['field_district']['und']['#options'] = _user_liveitchina_district_dropdown_options($selected);
*/
  if (isset($form_state['values']['profile_user']['field_city']['und'][0]['tid'])) {
    $city_selected = $form_state['values']['profile_user']['field_city']['und'][0]['tid'];
  }
  elseif(isset($form['profile_user']['field_city']['und']['#default_value'][0])) {
    $city_selected = $form['profile_user']['field_city']['und']['#default_value'][0];
  }
  else {
    $city_selected = key($options_city);
  }

  $area_options = _user_liveitchina_district_dropdown_options($city_selected, 'area');
  $area_selected = '';

  if (isset($form_state['values']['profile_user']['field_area']['und'][0]['tid'])) {
    $area_selected = $form_state['values']['profile_user']['field_area']['und'][0]['tid'];
  }
  elseif(isset($form['profile_user']['field_area']['und']['#default_value'][0])) {
    $area_selected = $form['profile_user']['field_area']['und']['#default_value'][0];
  }

  if ($area_selected == ''){
    $mode = next($area_options);
    $area_selected = key($area_options);
  }

  //add #ajax for the city
  $form['profile_user']['field_city']['und']['#options'] = $options_city;
  $form['profile_user']['field_city']['und']['#ajax'] = array(
      'callback' => '_liveitchina_dependent_dropdown_city_callback',
      'wrapper' => 'dropdown-select-area-replace',
  );  

  $form['profile_user']['field_area']['#prefix'] = '<div id="dropdown-select-area-replace">';
  $form['profile_user']['field_area']['#suffix'] = '</div>';
  $form['profile_user']['field_area']['#attributes']['class'][] = 'enabled-for-ajax';
  $form['profile_user']['field_area']['und']['#options'] = $area_options;
  $form['profile_user']['field_area']['und']['#ajax'] = array(
      'callback' => '_liveitchina_dependent_dropdown_area_callback',
      'wrapper' => 'dropdown-select-district-replace',
  );

  $form['profile_user']['field_district']['#prefix'] = '<div id="dropdown-select-district-replace">';
  $form['profile_user']['field_district']['#suffix'] = '</div>';
  $form['profile_user']['field_district']['#attributes']['class'][] = 'enabled-for-ajax';
  $form['profile_user']['field_district']['und']['#options'] = _user_liveitchina_district_dropdown_options($area_selected, 'district');
  
}

//*/

function _liveitchina_city_dropdown_options() {
  $options = array();
  $v = taxonomy_vocabulary_machine_name_load('liveitchina_city');
  $terms = taxonomy_get_tree($v->vid, 0 , 1);
  foreach ($terms as $term) {
    $options[$term->tid] = $term->name;
  }

  return $options;
}

function _user_liveitchina_district_dropdown_options($key = '', $text = 'city') {

  $options = array(''=>t('Select !text.', array('!text'=>$text)));
  if ($key){
    $v = taxonomy_vocabulary_machine_name_load('liveitchina_city');
    $terms = taxonomy_get_tree($v->vid, $key , 1);
    foreach ($terms as $term) {
      $options[$term->tid] = $term->name;
    }
    return $options;
  }
  
}
/*
function liveitchina_dependent_dropdown_city_callback($form, &$form_state) {
  $keys = array_keys($form);
  $profile_type = array_shift($keys);
  return $form[$profile_type]['field_district']['und'];
}
*/
function _liveitchina_dependent_dropdown_city_callback($form, &$form_state) {
  return $form['profile_user']['field_area'];
}

function _liveitchina_dependent_dropdown_area_callback($form, &$form_state) {
  return $form['profile_user']['field_district'];
}

/*
 * Implements hook_field_attach_presave();
 * 
 * Add automatic value for field_map;
 */
function user_liveitchina_field_attach_presave($entity_type, $entity){
  //check if it's a profile2 and have field_map
  $lang = 'und';
  if ($entity_type == 'profile2' && isset($entity->field_map)){
    $lang_field = (isset($entity->field_map[$lang])) ? $lang: 'und';
    //get the value of district
    if ($district = field_get_items('profile2', $entity, 'field_district')){
      $city = field_get_items('profile2', $entity, 'field_city');
      $district_tid = $district[0]['tid'];
      $city_tid = $city[0]['tid'];
      $load_term = array($district_tid, $city_tid);
      $address = taxonomy_term_load_multiple($load_term);
      $text_address = $address[$district_tid]->name . ', ' . $address[$city_tid]->name;
      $map = _liveitchina_get_map($text_address);
      $entity->field_map[$lang_field][0] = $map;
    }
  }
}

function _user_liveitchina_ds_display($field){
  $entity = $field['entity'];
  $user = user_load($entity->uid);
  $user_profile = profile2_load_by_user($entity->uid, 'user');
  $data = array();
  $display = array();

  return theme('liveitchina_profile_user', array(
    'display'=> $display,
    'profile'=>$user_profile,
    'user'=> $user
    )
  );
}

function _user_liveitchina_ds_actions($field){
  global $user;
  //print_r($field); exit;

  $profile = $field['entity'];
  $var = variable_get('profile_role_relationship', _profile2_liveitchina_role_relationship());
  $links = array();
  
  $requestee = $profile->uid;
  switch ($field['view_mode']){
    case 'exchange_partner_featured_view':
      $relationship = 2;
    break;
    case 'featured_view_mode':
      $relationship = 3;
    break;
    default:
      $relationship = 6;
  }
  $url_label = liveitchina_get_connect_label($relationship);
  $connect_url = 'connect/' . $requestee . '/request/'. $relationship;
  
    $links[] = array(
      'data' => l(t('See Availability'), $_GET["q"], array('fragment'=>'#')),
    );
    $links[] = array(
      //'data' => l(t('See Availability'), $_GET["q"], array('fragment'=>'#')),
      'data' => l(t($url_label), $connect_url),
    );  

  $data = theme('item_list',
    array('items' => $links,
      'attributes' => array(
        'class' => array(
          'user-actions',
          'clearfix'
        ),
      ),
    )
  );
  return $data;
}

function user_liveitchina_preprocess_user_profile(&$vars){
}

function _user_liveitchina_ds_profile_teaches($field){
  $entity = $field['entity'];
  $profile = profile2_load_by_user($entity->uid, 'tutor');
  return _user_liveitchina_teaches($profile);
}

function _user_liveitchina_teaches( $profile ){
  $lang_offered = array();
  $lang_others = array();
  if ($field_values = field_get_items('profile2', $profile, 'field_lang_offered')){
    foreach ($field_values as $value) {
      $lang_offered[] = $value['tid'];
    }
  }

  $field_others = ($profile->type == 'tutor')? 'field_tutor_others': 'field_off_exch_other';
  if ($field_values = field_get_items('profile2', $profile, $field_others)){
    foreach ($field_values as $value) {
      $lang_others[] = $value['tid'];
    }
  }
  $lang_display = (count($lang_offered)) ? implode(', ', facetapi_map_taxonomy_terms($lang_offered)): '';
  $lang_others = (count($lang_others))? ': '. implode(', ', facetapi_map_taxonomy_terms($lang_others)):'';
  return $lang_display . $lang_others;
}

function _user_liveitchina_ds_profile_cost($field){
  $entity = $field['entity'];
  $profile_user = profile2_load_by_user($entity->uid, 'user');
  $city = _liveitchina_field_get_field('profile2', $profile_user, 'field_city', 'tid');
  $profile_user = profile2_load_by_user($entity->uid, 'tutor');
  $cost_value = _liveitchina_field_get_field('profile2', $profile_user, 'field_user_tutor_price', 'value');
  $price = _liveitchina_price_table($city, $cost_value);
  return $price;
}

function _user_liveitchina_ds_profile_desc($field){
  $entity = $field['entity'];
  $profile_user = profile2_load_by_user($entity->uid, 'tutor');
  $desc = _liveitchina_field_get_field('profile2', $profile_user, 'field_summary', 'value');
  return $desc;
}

function _user_liveitchina_name_title($field){
  $entity = $field['entity'];
  $user_profile = user_load($entity->uid);
  $profile_user = profile2_load_by_user($entity->uid, 'user');
  $city = _liveitchina_field_get_field('profile2', $profile_user, 'field_city', 'tid');
  $city_name = facetapi_map_taxonomy_terms(array($city));
  return '<h2 class="block-title">'. l($user_profile->realname, 'profile-tutor/' . $user_profile->uid) .
      '<span class="field-city"> ('.$city_name[$city].')</span>'.
      '</h2>';
}

function _user_liveitchina_name_title_exchange_partner($field){
  $entity = $field['entity'];
  $user_profile = user_load($entity->uid);
  $profile_user = profile2_load_by_user($entity->uid, 'user');
  $city = _liveitchina_field_get_field('profile2', $profile_user, 'field_city', 'tid');
  $city_name = facetapi_map_taxonomy_terms(array($city));
  return '<h2 class="block-title">'. l($user_profile->realname, 'profile-exchange_partner/' . $user_profile->uid) .
        '<span class="field-city"> ('.$city_name[$city].')</span>'.
        '</h2>';
}

function user_liveitchina_form_user_register_form_alter(&$form, &$form_state, $form_id){
  $form['#prefix'] = '<div class="register-preface">LiveItChina.com is a social media platform for language learners. A free service that lets users share their unbiased learning experience. Find local teachers, ideal language exchange partners, compare, review and book courses at language schools. Learn a language and sign up for free!</div>';
}

function _user_liveitchina_rating_tutor($field){
  $entity = $field['entity'];
  $user_profile = user_load($entity->uid);
  $profile_user = profile2_load_by_user($entity->uid, 'tutor');
  $format = array('type' => 'fivestar_formatter_default',
                  'label' => 'hidden',
                  'settings' => array('text'=>'none',
                                      'expose' => 0,
                                      'widget' => array('fivestar_widget'=> drupal_get_path('module','liveitchina') . '/widget/star/star.css')));
  return render(field_view_field('profile2', $profile_user, 'field_rating',$format));
}

function _user_liveitchina_rating_exchange_partner($field){
  $entity = $field['entity'];
  $user_profile = user_load($entity->uid);
  $profile_user = profile2_load_by_user($entity->uid, 'exchange_partner');
  $format = array('type' => 'fivestar_formatter_default',
                  'label' => 'hidden',
                  'settings' => array('text'=>'none',
                                      'expose' => 0,
                                      'widget' => array('fivestar_widget'=> drupal_get_path('module','liveitchina') . '/widget/star/star.css')));
	return render(field_view_field('profile2', $profile_user, 'field_rating',$format));
}
