<?php

/**
  * Implements hook_views_api().
  */
function views_reply_reviews_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'views_reply_reviews'),
  );
}

/**
 * Implements hook_ds_fields_info().
 */
function views_reply_reviews_ds_fields_info($entity_type) {
  $fields = array();
  $fields['profile2']['profile_reviews'] = array(
    'title' => t('Profile Reviews'),
    'field_type' => DS_FIELD_TYPE_BLOCK,
    'properties' => array(
      'block' => 'views|user_review-block',
      'block_render' => DS_BLOCK_CONTENT,
    ),
  );

  return $fields;
}