 <?php
/*
 * Implements hook_field_attach_presave();
 * f
 * Add automatic value for field_map;
 * /
function user_liveitchina_field_attach_presave($entity_type, $entity){
  //check if it's a profile2 and have field_map
  $lang = 'und';
  if ($entity_type == 'taxonomy' && isset($entity->field_map)){
    $lang_field = (isset($entity->field_map[$lang])) ? $lang: 'und';
    //get the value of district
  }
}
//*/