<?php
module_load_include('inc', 'user_relationships_ui', 'user_relationships_ui.pages');

/*
 * Implements hook_menu().
 */
function user_relationships_liveitchina_menu() {
  $items = array();

  $items['user/%user/connections'] = array(
    'title' => 'My Connections',
    'access callback' => 'user_relationships_ui_check_access',
    'access arguments' => array('view', 1),
    'page callback' => 'user_relationships_liveitchina_page',
    'page arguments' => array(1),
    'file' => 'user_relationships_liveitchina.pages.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['user/%user/connections/list'] = array(
    'title' => 'All Connections',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
    'access callback' => 'user_relationships_ui_check_access',
    'access arguments' => array('view', 1),
  );

  $items['user/%user/connections/received'] = array(
    'title' => 'Received requests',
    'title callback' => 'user_relationships_ui_title_callback_pending',
    'title arguments' => array('requestee_id', 1),
    'access callback' => 'user_relationships_ui_check_access',
    'access arguments' => array('approve', 1),
    'type' => MENU_NORMAL_ITEM,
    'weight' => -9,
    'page callback' => 'user_relationships_pending_requests_page',
    'page arguments' => array('requestee_id', 1),
    'file' => 'user_relationships_ui.pages.inc',
    'file path'=> drupal_get_path('module', 'user_relationships_ui'),
  );

  $items['user/%user/connections/sent'] = array(
    'title' => 'Sent requests',
    'title callback' => 'user_relationships_ui_title_callback_pending',
    'title arguments' => array('requester_id', 1),
    'access callback' => 'user_relationships_ui_check_access',
    'access arguments' => array('request', 1),
    'type' => MENU_NORMAL_ITEM,
    'weight' => -8,
    'page callback' => 'user_relationships_pending_requests_page',
    'page arguments' => array('requester_id', 1),
    'file' => 'user_relationships_ui.pages.inc',
    'file path'=> drupal_get_path('module', 'user_relationships_ui'),
  );

  $rels = user_relationships_types_load();
  foreach ($rels as $rtid => $relationship) {
    $items["user/%user/connections/{$rtid}"] = array(
      'title' => $relationship->plural_name ? $relationship->plural_name : $relationship->name,
      'type' => MENU_LOCAL_TASK,
      'access callback' => 'user_relationships_ui_check_access',
      'access arguments' => array('view', 1, 3),
      'page callback' => 'user_relationships_liveitchina_page',
      'page arguments' => array(1, 3),
      'file' => 'user_relationships_liveitchina.pages.inc',
    );
  }

  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function user_relationships_liveitchina_menu_alter(&$items) {
  $items['user/%user/connections']['type'] = MENU_NORMAL_ITEM;
}
/*
 * Implements hook_user_relationships_ui_table_row_alter().
*/
function user_relationships_liveitchina_user_relationships_ui_table_row_alter(&$row, $relationship, $account) {
  $row[2] = ur_tt("user_relationships:rtid:$relationship->rtid:name", $relationship->name);
  //print_r($row);
  //exit;
}